package com.sr.biz.freightbit.core.entity;
// Generated May 10, 2014 12:10:47 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Clients generated by hbm2java
 */
@Entity
@Table(name="clients"
    ,catalog="freightbit"
)
public class Client  implements java.io.Serializable {


     private Integer clientId;
     private String clientName;
     private String addressLine1;
     private String addressLine2;
     private String city;
     private String state;
     private String zip;
     private String phone;
     private String mobile;
     private String fax;
     private String email;
     private String website;
     private Date createdTimestamp;
     private String createdBy;
     private Date modifiedTimestamp;
     private String modifiedBy;

    public Client() {
    }

	
    public Client(String clientName, Date createdTimestamp, String createdBy, Date modifiedTimestamp, String modifiedBy) {
        this.clientName = clientName;
        this.createdTimestamp = createdTimestamp;
        this.createdBy = createdBy;
        this.modifiedTimestamp = modifiedTimestamp;
        this.modifiedBy = modifiedBy;
    }
    
    /*public Client(String clientName, String addressLine1, String addressLine2, String city, String state, String zip, String phone, String mobile, String fax, String email, String website, Date createdTimestamp, String createdBy, Date modifiedTimestamp, String modifiedBy) {
       this.clientName = clientName;
       this.addressLine1 = addressLine1;
       this.addressLine2 = addressLine2;
       this.city = city;
       this.state = state;
       this.zip = zip;
       this.phone = phone;
       this.mobile = mobile;
       this.fax = fax;
       this.email = email;
       this.website = website;
       this.createdTimestamp = createdTimestamp;
       this.createdBy = createdBy;
       this.modifiedTimestamp = modifiedTimestamp;
       this.modifiedBy = modifiedBy;
    }*/
   
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="clientId", unique=true, nullable=false)
    public Integer getClientId() {
        return this.clientId;
    }
    
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    
    @Column(name="clientName", nullable=false, length=50)
    public String getClientName() {
        return this.clientName;
    }
    
    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    
    @Column(name="addressLine1", length=50)
    public String getAddressLine1() {
        return this.addressLine1;
    }
    
    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }

    
    @Column(name="addressLine2")
    public String getAddressLine2() {
        return this.addressLine2;
    }
    
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }

    
    @Column(name="city", length=50)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="state", length=50)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    
    @Column(name="zip", length=50)
    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }

    
    @Column(name="phone", length=30)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="mobile", length=30)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    
    @Column(name="fax", length=30)
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    
    @Column(name="email", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="website", length=50)
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdTimestamp", nullable=false, length=19)
    public Date getCreatedTimestamp() {
        return this.createdTimestamp;
    }
    
    public void setCreatedTimestamp(Date createdTimestamp) {
        this.createdTimestamp = createdTimestamp;
    }

    
    @Column(name="createdBy", nullable=false, length=10)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modifiedTimestamp", nullable=false, length=19)
    public Date getModifiedTimestamp() {
        return this.modifiedTimestamp;
    }
    
    public void setModifiedTimestamp(Date modifiedTimestamp) {
        this.modifiedTimestamp = modifiedTimestamp;
    }

    
    @Column(name="modifiedBy", nullable=false, length=10)
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }


}


