package com.sr.biz.freightbit.core.entity;

// Generated May 2, 2014 5:40:15 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GroupUser generated by hbm2java
 *
 */
@Entity
@Table(name = "group_user", catalog = "freightbit")
public class GroupUser implements java.io.Serializable {

	private Integer groupUserId;
	private Integer clientId;
	private Integer userId;
	private Integer groupId;

	public GroupUser() {
	}

	public GroupUser(Integer groupUserId, Integer clientId, Integer userId, Integer groupId) {
		this.groupUserId = groupUserId;
		this.clientId = clientId;
		this.userId = userId;
		this.groupId = groupId;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "groupUserId", unique = true, nullable = false)
	public Integer getGroupUserId() {
		return this.groupUserId;
	}

	public void setGroupUserId(Integer groupUserId) {
		this.groupUserId = groupUserId;
	}

	@Column(name = "clientId", nullable = false)
	public Integer getClientId() {
		return this.clientId;
	}

	public void setClientId(Integer clientId) {
		this.clientId = clientId;
	}

	@Column(name = "userId", nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "groupId", nullable = false)
	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

}
