package com.sr.biz.freightbit.core.entity;

// Generated May 2, 2014 5:40:15 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Permissionusergroup generated by hbm2java
 */
@Entity
@Table(name = "permission_user_group", catalog = "freightbit")
public class PermissionUserGroup implements java.io.Serializable {

    private long permissionId;
    private long clientId;
    private Long userId;
    private Long groupId;
    private Long projectId;
    private Long value;

    public PermissionUserGroup() {
    }

    public PermissionUserGroup(long permissionId, long clientId) {
        this.permissionId = permissionId;
        this.clientId = clientId;
    }

    public PermissionUserGroup(long permissionId, long clientId, Long userId,
                               Long groupId, Long projectId, Long value) {
        this.permissionId = permissionId;
        this.clientId = clientId;
        this.userId = userId;
        this.groupId = groupId;
        this.projectId = projectId;
        this.value = value;
    }

    @Id
    @Column(name = "permissionId", unique = true, nullable = false)
    public long getPermissionId() {
        return this.permissionId;
    }

    public void setPermissionId(long permissionId) {
        this.permissionId = permissionId;
    }

    @Column(name = "clientId", nullable = false)
    public long getClientId() {
        return this.clientId;
    }

    public void setClientId(long clientId) {
        this.clientId = clientId;
    }

    @Column(name = "userId")
    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @Column(name = "groupId")
    public Long getGroupId() {
        return this.groupId;
    }

    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    @Column(name = "projectId")
    public Long getProjectId() {
        return this.projectId;
    }

    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    @Column(name = "value")
    public Long getValue() {
        return this.value;
    }

    public void setValue(Long value) {
        this.value = value;
    }

}
