package com.sr.biz.freightbit.core.entity;

// Generated May 2, 2014 5:40:15 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Permissionusergroup generated by hbm2java
 */
@Entity
@Table(name = "permission_user_group", catalog = "freightbit")
public class PermissionUserGroup implements java.io.Serializable {

    private Integer permissionId;
    private Integer clientId;
    private Integer userId;
    private Integer groupId;
    private Integer projectId;
    private Integer value;

    public PermissionUserGroup() {
    }

    public PermissionUserGroup(Integer permissionId, Integer clientId) {
        this.permissionId = permissionId;
        this.clientId = clientId;
    }

    public PermissionUserGroup(Integer permissionId, Integer clientId, Integer userId,
                               Integer groupId, Integer projectId, Integer value) {
        this.permissionId = permissionId;
        this.clientId = clientId;
        this.userId = userId;
        this.groupId = groupId;
        this.projectId = projectId;
        this.value = value;
    }

    @Id
    @Column(name = "permissionId", unique = true, nullable = false)
    public Integer getPermissionId() {
        return this.permissionId;
    }

    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    @Column(name = "clientId", nullable = false)
    public Integer getClientId() {
        return this.clientId;
    }

    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    @Column(name = "userId")
    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Column(name = "groupId")
    public Integer getGroupId() {
        return this.groupId;
    }

    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    @Column(name = "projectId")
    public Integer getProjectId() {
        return this.projectId;
    }

    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    @Column(name = "value")
    public Integer getValue() {
        return this.value;
    }

    public void setValue(Integer value) {
        this.value = value;
    }

}
