package com.sr.biz.freightbit.core.entity;

// Generated May 2, 2014 5:40:15 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Permission generated by hbm2java
 */
@Entity
@Table(name = "permission", catalog = "freightbit", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Permission implements java.io.Serializable {

    private Integer permissionId;
    private Integer clientId;
    private String name;
    private String description;
    private Date creationDate;
    private Date modifiedDate;

    public Permission() {
    }

    public Permission(Integer permissionId, Integer clientId, String name,
                      Date creationDate, Date modifiedDate) {
        this.permissionId = permissionId;
        this.clientId = clientId;
        this.name = name;
        this.creationDate = creationDate;
        this.modifiedDate = modifiedDate;
    }

    public Permission(Integer permissionId, Integer clientId, String name,
                      String description, Date creationDate, Date modifiedDate) {
        this.permissionId = permissionId;
        this.clientId = clientId;
        this.name = name;
        this.description = description;
        this.creationDate = creationDate;
        this.modifiedDate = modifiedDate;
    }

    @Id
    @GeneratedValue
    @Column(name = "permissionId", unique = true, nullable = false)
    public Integer getPermissionId() {
        return this.permissionId;
    }

    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    @Column(name = "clientId", nullable = false)
    public Integer getClientId() {
        return this.clientId;
    }

    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    @Column(name = "name", unique = true, nullable = false, length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "description")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "creationDate", nullable = false)
    public Date getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @Column(name = "modifiedDate", nullable = false)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }

    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

}
