package com.sr.biz.freightbit.order.entity;
// Generated Jun 4, 2014 2:09:24 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name="orders"
    ,catalog="freightbit"
    , uniqueConstraints = @UniqueConstraint(columnNames="orderNumber") 
)
public class Orders  implements java.io.Serializable {


     private Integer orderId;
     private Integer clientId;
     private Integer orderNumber;
     private String serviceType;
     private String serviceMode;
     private String notificationType;
     private Date orderDate;
     private String paymentMode;
     private Integer quantity;
     private String size;
     private String classification;
     private Double estimatedWeight;
     private Double declaredValue;
     private String commodity;
     private String comments;
     private Double rate;
     private String orderStatus;
     private String vendorCode;
     private String truckCode;
     private String trailerCode;
     private String driverCode;
     private String vesselNumber;
     private String accountRep;
     private Date createdTimestamp;
     private String createdBy;
     private Date modifiedTimestamp;
     private String modifiedBy;
     private Integer customerId;
     private String portOfDestination;
     private String portOfOrigin;

    public Orders() {
    }

	
    public Orders(Integer clientId, Integer orderNumber, String serviceType, String serviceMode, String notificationType, Date orderDate, String paymentMode, Integer quantity, String size, String classification, Double estimatedWeight, Double declaredValue, String commodity, String comments, Double rate, String orderStatus, Date createdTimestamp, String createdBy, Date modifiedTimestamp, String modifiedBy, Integer customerId, String portOfDestination, String portOfOrigin) {
        this.clientId = clientId;
        this.orderNumber = orderNumber;
        this.serviceType = serviceType;
        this.serviceMode = serviceMode;
        this.notificationType = notificationType;
        this.orderDate = orderDate;
        this.paymentMode = paymentMode;
        this.quantity = quantity;
        this.size = size;
        this.classification = classification;
        this.estimatedWeight = estimatedWeight;
        this.declaredValue = declaredValue;
        this.commodity = commodity;
        this.comments = comments;
        this.rate = rate;
        this.orderStatus = orderStatus;
        this.createdTimestamp = createdTimestamp;
        this.createdBy = createdBy;
        this.modifiedTimestamp = modifiedTimestamp;
        this.modifiedBy = modifiedBy;
        this.customerId = customerId;
        this.portOfDestination = portOfDestination;
        this.portOfOrigin = portOfOrigin;
    }
    public Orders(Integer clientId, Integer orderNumber, String serviceType, String serviceMode, String notificationType, Date orderDate, String paymentMode, Integer quantity, String size, String classification, Double estimatedWeight, Double declaredValue, String commodity, String comments, Double rate, String orderStatus, String vendorCode, String truckCode, String trailerCode, String driverCode, String vesselNumber, String accountRep, Date createdTimestamp, String createdBy, Date modifiedTimestamp, String modifiedBy, Integer customerId, String portOfDestination, String portOfOrigin) {
       this.clientId = clientId;
       this.orderNumber = orderNumber;
       this.serviceType = serviceType;
       this.serviceMode = serviceMode;
       this.notificationType = notificationType;
       this.orderDate = orderDate;
       this.paymentMode = paymentMode;
       this.quantity = quantity;
       this.size = size;
       this.classification = classification;
       this.estimatedWeight = estimatedWeight;
       this.declaredValue = declaredValue;
       this.commodity = commodity;
       this.comments = comments;
       this.rate = rate;
       this.orderStatus = orderStatus;
       this.vendorCode = vendorCode;
       this.truckCode = truckCode;
       this.trailerCode = trailerCode;
       this.driverCode = driverCode;
       this.vesselNumber = vesselNumber;
       this.accountRep = accountRep;
       this.createdTimestamp = createdTimestamp;
       this.createdBy = createdBy;
       this.modifiedTimestamp = modifiedTimestamp;
       this.modifiedBy = modifiedBy;
       this.customerId = customerId;
       this.portOfDestination = portOfDestination;
       this.portOfOrigin = portOfOrigin;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="orderId", unique=true, nullable=false)
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    
    @Column(name="clientId", nullable=false)
    public Integer getClientId() {
        return this.clientId;
    }
    
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    
    @Column(name="orderNumber", unique=true, nullable=false)
    public Integer getOrderNumber() {
        return this.orderNumber;
    }
    
    public void setOrderNumber(Integer orderNumber) {
        this.orderNumber = orderNumber;
    }

    
    @Column(name="serviceType", nullable=false, length=10)
    public String getServiceType() {
        return this.serviceType;
    }
    
    public void setServiceType(String serviceType) {
        this.serviceType = serviceType;
    }

    
    @Column(name="serviceMode", nullable=false, length=10)
    public String getServiceMode() {
        return this.serviceMode;
    }
    
    public void setServiceMode(String serviceMode) {
        this.serviceMode = serviceMode;
    }

    
    @Column(name="notificationType", nullable=false, length=10)
    public String getNotificationType() {
        return this.notificationType;
    }
    
    public void setNotificationType(String notificationType) {
        this.notificationType = notificationType;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="orderDate", nullable=false, length=10)
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    
    @Column(name="paymentMode", nullable=false, length=10)
    public String getPaymentMode() {
        return this.paymentMode;
    }
    
    public void setPaymentMode(String paymentMode) {
        this.paymentMode = paymentMode;
    }

    
    @Column(name="quantity", nullable=false)
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="size", nullable=false, length=10)
    public String getSize() {
        return this.size;
    }
    
    public void setSize(String size) {
        this.size = size;
    }

    
    @Column(name="classification", nullable=false, length=50)
    public String getClassification() {
        return this.classification;
    }
    
    public void setClassification(String classification) {
        this.classification = classification;
    }

    
    @Column(name="estimatedWeight", nullable=false, precision=12, scale=0)
    public Double getEstimatedWeight() {
        return this.estimatedWeight;
    }
    
    public void setEstimatedWeight(Double estimatedWeight) {
        this.estimatedWeight = estimatedWeight;
    }

    
    @Column(name="declaredValue", nullable=false, precision=12, scale=0)
    public Double getDeclaredValue() {
        return this.declaredValue;
    }
    
    public void setDeclaredValue(Double declaredValue) {
        this.declaredValue = declaredValue;
    }

    
    @Column(name="commodity", nullable=false, length=50)
    public String getCommodity() {
        return this.commodity;
    }
    
    public void setCommodity(String commodity) {
        this.commodity = commodity;
    }

    
    @Column(name="comments", nullable=false)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

    
    @Column(name="rate", nullable=false, precision=12, scale=0)
    public Double getRate() {
        return this.rate;
    }
    
    public void setRate(Double rate) {
        this.rate = rate;
    }

    
    @Column(name="orderStatus", nullable=false, length=10)
    public String getOrderStatus() {
        return this.orderStatus;
    }
    
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    
    @Column(name="vendorCode", length=10)
    public String getVendorCode() {
        return this.vendorCode;
    }
    
    public void setVendorCode(String vendorCode) {
        this.vendorCode = vendorCode;
    }

    
    @Column(name="truckCode", length=10)
    public String getTruckCode() {
        return this.truckCode;
    }
    
    public void setTruckCode(String truckCode) {
        this.truckCode = truckCode;
    }

    
    @Column(name="trailerCode", length=10)
    public String getTrailerCode() {
        return this.trailerCode;
    }
    
    public void setTrailerCode(String trailerCode) {
        this.trailerCode = trailerCode;
    }

    
    @Column(name="driverCode", length=10)
    public String getDriverCode() {
        return this.driverCode;
    }
    
    public void setDriverCode(String driverCode) {
        this.driverCode = driverCode;
    }

    
    @Column(name="vesselNumber", length=50)
    public String getVesselNumber() {
        return this.vesselNumber;
    }
    
    public void setVesselNumber(String vesselNumber) {
        this.vesselNumber = vesselNumber;
    }

    
    @Column(name="accountRep", length=10)
    public String getAccountRep() {
        return this.accountRep;
    }
    
    public void setAccountRep(String accountRep) {
        this.accountRep = accountRep;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdTimestamp", nullable=false, length=19)
    public Date getCreatedTimestamp() {
        return this.createdTimestamp;
    }
    
    public void setCreatedTimestamp(Date createdTimestamp) {
        this.createdTimestamp = createdTimestamp;
    }

    
    @Column(name="createdBy", nullable=false, length=10)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modifiedTimestamp", nullable=false, length=19)
    public Date getModifiedTimestamp() {
        return this.modifiedTimestamp;
    }
    
    public void setModifiedTimestamp(Date modifiedTimestamp) {
        this.modifiedTimestamp = modifiedTimestamp;
    }

    
    @Column(name="modifiedBy", nullable=false, length=10)
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    
    @Column(name="customerId", nullable=false)
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    
    @Column(name="portOfDestination", nullable=false, length=45)
    public String getPortOfDestination() {
        return this.portOfDestination;
    }
    
    public void setPortOfDestination(String portOfDestination) {
        this.portOfDestination = portOfDestination;
    }

    
    @Column(name="portOfOrigin", nullable=false, length=45)
    public String getPortOfOrigin() {
        return this.portOfOrigin;
    }
    
    public void setPortOfOrigin(String portOfOrigin) {
        this.portOfOrigin = portOfOrigin;
    }




}



