package com.sr.biz.freightbit.order.entity;
//Generated Jun 4, 2014 2:09:24 PM by Hibernate Tools 3.6.0


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
* Orderstops generated by hbm2java
*/
@Entity
@Table(name="orderstops"
 ,catalog="freightbit"
)
public class OrderStops  implements java.io.Serializable {


  private Integer orderStopId;
  private Integer clientId;
  private Integer orderId;
  private Integer stopNumber;
  private String stopType;
  private String stopName;
  private Integer addressId;
  private Integer contactId;
  private Date appointmentDate;
  private Date appointmentTime;
  private Date createdTimestamp;
  private String createdBy;
  private Date modifiedTimestamp;
  private String modifiedBy;

 public OrderStops() {
 }

 public OrderStops(Integer clientId, Integer orderId, Integer stopNumber, String stopType, String stopName, Integer addressId, Integer contactId, Date appointmentDate, Date appointmentTime, Date createdTimestamp, String createdBy, Date modifiedTimestamp, String modifiedBy) {
    this.clientId = clientId;
    this.orderId = orderId;
    this.stopNumber = stopNumber;
    this.stopType = stopType;
    this.stopName = stopName;
    this.addressId = addressId;
    this.contactId = contactId;
    this.appointmentDate = appointmentDate;
    this.appointmentTime = appointmentTime;
    this.createdTimestamp = createdTimestamp;
    this.createdBy = createdBy;
    this.modifiedTimestamp = modifiedTimestamp;
    this.modifiedBy = modifiedBy;
 }

  @Id @GeneratedValue(strategy=IDENTITY)

 
 @Column(name="orderStopId", unique=true, nullable=false)
 public Integer getOrderStopId() {
     return this.orderStopId;
 }
 
 public void setOrderStopId(Integer orderStopId) {
     this.orderStopId = orderStopId;
 }

 
 @Column(name="clientId", nullable=false)
 public int getClientId() {
     return this.clientId;
 }
 
 public void setClientId(int clientId) {
     this.clientId = clientId;
 }

 
 @Column(name="orderId", nullable=false)
 public int getOrderId() {
     return this.orderId;
 }
 
 public void setOrderId(int orderId) {
     this.orderId = orderId;
 }

 
 @Column(name="stopNumber", nullable=false)
 public int getStopNumber() {
     return this.stopNumber;
 }
 
 public void setStopNumber(int stopNumber) {
     this.stopNumber = stopNumber;
 }

 
 @Column(name="stopType", nullable=false, length=10)
 public String getStopType() {
     return this.stopType;
 }
 
 public void setStopType(String stopType) {
     this.stopType = stopType;
 }

 
 @Column(name="stopName", nullable=false, length=50)
 public String getStopName() {
     return this.stopName;
 }
 
 public void setStopName(String stopName) {
     this.stopName = stopName;
 }

 
 @Column(name="addressId", nullable=false)
 public Integer getAddressId() {
     return this.addressId;
 }
 
 public void setAddressId(Integer addressId) {
     this.addressId = addressId;
 }

 
 @Column(name="contactId", nullable=false)
 public int getContactId() {
     return this.contactId;
 }
 
 public void setContactId(int contactId) {
     this.contactId = contactId;
 }

 @Temporal(TemporalType.DATE)
 @Column(name="appointmentDate", nullable=false, length=10)
 public Date getAppointmentDate() {
     return this.appointmentDate;
 }
 
 public void setAppointmentDate(Date appointmentDate) {
     this.appointmentDate = appointmentDate;
 }

 @Temporal(TemporalType.TIME)
 @Column(name="appointmentTime", nullable=false, length=8)
 public Date getAppointmentTime() {
     return this.appointmentTime;
 }
 
 public void setAppointmentTime(Date appointmentTime) {
     this.appointmentTime = appointmentTime;
 }

 @Temporal(TemporalType.TIMESTAMP)
 @Column(name="createdTimestamp", nullable=false, length=19)
 public Date getCreatedTimestamp() {
     return this.createdTimestamp;
 }
 
 public void setCreatedTimestamp(Date createdTimestamp) {
     this.createdTimestamp = createdTimestamp;
 }

 
 @Column(name="createdBy", nullable=false, length=10)
 public String getCreatedBy() {
     return this.createdBy;
 }
 
 public void setCreatedBy(String createdBy) {
     this.createdBy = createdBy;
 }

 @Temporal(TemporalType.TIMESTAMP)
 @Column(name="modifiedTimestamp", nullable=false, length=19)
 public Date getModifiedTimestamp() {
     return this.modifiedTimestamp;
 }
 
 public void setModifiedTimestamp(Date modifiedTimestamp) {
     this.modifiedTimestamp = modifiedTimestamp;
 }

 
 @Column(name="modifiedBy", nullable=false, length=10)
 public String getModifiedBy() {
     return this.modifiedBy;
 }
 
 public void setModifiedBy(String modifiedBy) {
     this.modifiedBy = modifiedBy;
 }

}



