package com.sr.biz.freightbit.order.entity;
//Generated Jun 4, 2014 2:09:24 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
* Orderitems generated by hbm2java
*/
@Entity
@Table(name="orderitems"
 ,catalog="freightbit"
)
public class OrderItems  implements java.io.Serializable {


  private Integer orderItemId;
  private Integer orderId;
  private Integer clientId;
  private Integer quantity;
  private String size;
  private Double estimatedWeight;
  private Double declaredValue;
  private String commodity;
  private String comments;
  private Date createdTimestamp;
  private String createdBy;
  private Date modifiedTimestamp;
  private String modifiedBy;

 public OrderItems() {
 }

 public OrderItems(Integer orderId, Integer clientId, Integer quantity, String size, Double estimatedWeight, Double declaredValue, String commodity, String comments, Date createdTimestamp, String createdBy, Date modifiedTimestamp, String modifiedBy) {
    this.orderId = orderId;
    this.clientId = clientId;
    this.quantity = quantity;
    this.size = size;
    this.estimatedWeight = estimatedWeight;
    this.declaredValue = declaredValue;
    this.commodity = commodity;
    this.comments = comments;
    this.createdTimestamp = createdTimestamp;
    this.createdBy = createdBy;
    this.modifiedTimestamp = modifiedTimestamp;
    this.modifiedBy = modifiedBy;
 }

  @Id @GeneratedValue(strategy=IDENTITY)

 
 @Column(name="orderItemId", unique=true, nullable=false)
 public Integer getOrderItemId() {
     return this.orderItemId;
 }
 
 public void setOrderItemId(Integer orderItemId) {
     this.orderItemId = orderItemId;
 }

 
 @Column(name="orderId", nullable=false)
 public int getOrderId() {
     return this.orderId;
 }
 
 public void setOrderId(int orderId) {
     this.orderId = orderId;
 }

 
 @Column(name="clientId", nullable=false)
 public int getClientId() {
     return this.clientId;
 }
 
 public void setClientId(int clientId) {
     this.clientId = clientId;
 }

 
 @Column(name="quantity", nullable=false)
 public int getQuantity() {
     return this.quantity;
 }
 
 public void setQuantity(int quantity) {
     this.quantity = quantity;
 }

 
 @Column(name="size", nullable=false, length=10)
 public String getSize() {
     return this.size;
 }
 
 public void setSize(String size) {
     this.size = size;
 }

 
 @Column(name="estimatedWeight", nullable=false, precision=12, scale=0)
 public Double getEstimatedWeight() {
     return this.estimatedWeight;
 }
 
 public void setEstimatedWeight(Double estimatedWeight) {
     this.estimatedWeight = estimatedWeight;
 }

 
 @Column(name="declaredValue", nullable=false, precision=12, scale=0)
 public Double getDeclaredValue() {
     return this.declaredValue;
 }
 
 public void setDeclaredValue(Double declaredValue) {
     this.declaredValue = declaredValue;
 }

 
 @Column(name="commodity", nullable=false, length=50)
 public String getCommodity() {
     return this.commodity;
 }
 
 public void setCommodity(String commodity) {
     this.commodity = commodity;
 }

 
 @Column(name="comments", nullable=false)
 public String getComments() {
     return this.comments;
 }
 
 public void setComments(String comments) {
     this.comments = comments;
 }

 @Temporal(TemporalType.TIMESTAMP)
 @Column(name="createdTimestamp", nullable=false, length=19)
 public Date getCreatedTimestamp() {
     return this.createdTimestamp;
 }
 
 public void setCreatedTimestamp(Date createdTimestamp) {
     this.createdTimestamp = createdTimestamp;
 }

 
 @Column(name="createdBy", nullable=false, length=10)
 public String getCreatedBy() {
     return this.createdBy;
 }
 
 public void setCreatedBy(String createdBy) {
     this.createdBy = createdBy;
 }

 @Temporal(TemporalType.TIMESTAMP)
 @Column(name="modifiedTimestamp", nullable=false, length=19)
 public Date getModifiedTimestamp() {
     return this.modifiedTimestamp;
 }
 
 public void setModifiedTimestamp(Date modifiedTimestamp) {
     this.modifiedTimestamp = modifiedTimestamp;
 }

 
 @Column(name="modifiedBy", nullable=false, length=10)
 public String getModifiedBy() {
     return this.modifiedBy;
 }
 
 public void setModifiedBy(String modifiedBy) {
     this.modifiedBy = modifiedBy;
 }




}



